name: Docker Image CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
 
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}   
      run: |        
        docker build . --file Dockerfile --tag omkar263/devops_task2_img:v1
        docker login -u $USER -p $PASS        
        docker push omkar263/devops_task2_img:v1
